### ISSUE TITLE
the emulator does not work for me on samsung galaxy 9

### ISSUE THREAD

**Issue by ricardojackson** [SachinVin/citra_android#10]
hello I have a samsung galaxy s9 and when I give a game the screen comes out in black and I get in the main menu of citra where you give the games my mobile is high-end and I do not understand why the 3ds emulator does not work for someone can help me I thank you thank you

**Comment by Paraskevidis** [comment]
If I understand you correctly the game won't open and you get kicked to the main menu?

If you phone doesn't have snapdragon then nothing will work because something is missing in the GPU drivers, we can only wait for SachinVin or someone else to find a workaround or our phones to get driver updates

**Comment by ricardojackson** [comment]
to me the ps2 emulator works on me android less I would like to play on my mobile wing 3ds but e seen on a YouTube video that on a samsung galaxy s9 plus works the citra emulator I hope it will be fixed citra for the samsung galaxy s9 because I would like to play wing 3ds on my mobile I hope it solves it

**Comment by kenan1099** [comment]
Just to add to what Paras said, you can always check which cpu you have by downloading an app like CPU-Z

**Comment by ricardojackson** [comment]
If I download that I will work or similar mobile phone because I'm interested in playing 3ds or I want to wait for it to be fixed, please help me please

**Comment by ricardojackson** [comment]
if my processor is Samsung Exynos 9810, 10 nm, 64 bits, octa-core or I want to wait for another citra update so that the games work well or someone to fix it because my cell phone is high-end I do not understand why not it works for me someone helps me thanks

**Comment by Paraskevidis** [comment]
It doesn't matter if your phone is the best, it has Exynos so it won't work now.
I have a medium range phone and I can run a few PS2 games with playable speeds with Damonps2 but because I don't have snapdragon I can't use this citra port.

@kenan I'm not a Paras! x4 weakness to fire type moves ewww!

**Comment by kenan1099** [comment]
@Paraskevidis
I wouldn't wanna be paras either , it's evolved form is just a zombie !

**Comment by ricardojackson** [comment]
then you're telling me that the emulator will not work on my phone up to a hundred point with the 3ds emulator or until it is fixed

**Comment by ricardojackson** [comment]
@Paraskevidis
then you're telling me that the emulator will not work on my phone up to a hundred point with the 3ds emulator or until it is fixed

**Comment by SachinVin** [comment]
@ricardojackson until it is fixed(I dont know when).

I'll be closing this because it is the same as #8
