### ISSUE TITLE
Super Mario 3d land

### ISSUE THREAD

**Issue by Chris2918** [SachinVin/citra_android#111]
When I try to play super Mario 3d land, it crashed.
The emulator.
I try to play again and doesn't work.
I know some games will not work for the Android version

**Comment by SachinVin** [comment]
What device do you have? and does it happen with other games

**Comment by bobbymc1985** [comment]
It works on my Xperia xz2. It was one of the first games I tested

**Comment by Chris2918** [comment]
My device is a Alcatel A30 Tablet

**Comment by SemRage** [comment]
Work on zen phone2 ?

Em 30/11/2018 08:32, "SachinVin" <notifications@github.com> escreveu:

What device do you have? and does it happen with other games

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SachinVin/citra_android/issues/111#issuecomment-443161516>,
or mute the thread

**Comment by FrOsT1601** [comment]
Yeah also have a problem I can start the game but as soon as I wanna create a new world it shows me that I don't have a mii character and the game closes

**Comment by HelloOO7** [comment]
Dump a save file from your 3DS.

A NAND/sysarchive dump could work too but I haven't tried that.

**Comment by Chris2918** [comment]
I have returned to this topic. I have abandoned the Android version and will close this topic. I have decided to go on to the PC version. Plus I have a high-end pc now. I am not sure how it will perform.
Thank you for your consideration.

**Comment by Chris2918** [comment]
Plus, happy new year everyone. :)
