### ISSUE TITLE
LATEST BUILD DL

### ISSUE THREAD

**Issue by JReverse** [SachinVin/citra_android#130]
https://www.sendspace.com/file/dom2qq

YW PEEPS

**Comment by Emulatorer** [comment]
What's new?

**Comment by Juxstin** [comment]
@Emulatorer has latest commits. @DarkXLord20 yes virustotal it

**Comment by DarkXLord20** [comment]
Seems little bit slower

**Comment by Priyam005** [comment]
I just want a build which can atleast get me 7fps on mediatek

**Comment by Anshc06** [comment]
Need a mirror link. The link is not working

**Comment by DarkXLord20** [comment]
Old Version faster on exynos

**Comment by HelloOO7** [comment]
Is this a debug or release build? Debug builds tend to be slower. Know that you should not download unofficial builds unless you know the risks. Official sources of releases are this repo's release page and the CI at https://ci.appveyor.com/project/SachinVin/citra-android/build/artifacts . Juxstin's build has actually been there for 11 days, it just looks like that nobody here actually knows this exists.

@Juxstin Do you think this belongs into an issue tracker? Well, no, it does not. But I think it should be kept for people to go to the CI for current builds. Nothing personal, but we do not want unofficial builds to become a trend as it might result in people crying in the issue tracker because they downloaded a virus.
