### ISSUE TITLE
Note 9 black screen

### ISSUE THREAD

**Issue by robbanks10** [SachinVin/citra_android#173]
Using a decrypted 3ds ROM of Animal Crossing New Leaf. Black screen with only the controls showing.

**Comment by ivanmendozalawrence** [comment]
You might have downloaded a corrupted .3ds file try redownloading the whole rom and try again

**Comment by robbanks10** [comment]
I redownloaded and still nothing. Redacted

**Comment by HelloOO7** [comment]
This is not a place to discuss piracy, you know. Nintendo takes every opportunity to sue emulators, so don't make it easy for them by talking about illegal ROMs in an issue tracker.

**Comment by robbanks10** [comment]
Apologies, statement redacted

**Comment by BelleNottelling** [comment]
Piracy and emulation CAN NOT go together.
Period, it's more than just Nintendo suing emulators and ROM sites, downloaded ROMs can also include mods and patches that break the emulator, but if an issue is submitted with them, it is a false issue that can only distract from how the emulator performs, or potentially causes work on a non-issue.
Emulators and their teams do not support piracy for these reasons, 


Xenia doesn't allow piracy `Discussing illegal activities will get you banned. No warnings.`

CXBX-Reloaded Doesn't allow it (Although this isn't clearly states on the readme of their game compatibility list & emulator repository, they don't work with it at all and avoid it)

Citra doesn't allow it `Downloading commercial games is illegal and thus strongly frowned upon by the Citra developers.`

I can keep going, but my point is made. Please, learn how to obtain these ROM files legally, if you are incapable of that then at least remain off of the forums for emulators as they don't need legal issues from it. I'm sorry if that is harsh, but there is not middle grey line of safety with piracy.
For obtaining a 3DS ROM: https://citra-emu.org/wiki/dumping-game-cartridges/
Thank you for understanding. 

Edit: Retracting a statement will not get you out of legal issues, if you smash someone's head with a bat and then get called out for it by the police and say "sorry, I take it back" you will still get into trouble because you smashed someone's head in with a bat.

**Comment by robbanks10** [comment]
Your reply wasn't harsh, it was rational, truthful and well-grounded. Appreciated.

**Comment by BelleNottelling** [comment]
Thank you
