### ISSUE TITLE
Neon Error

### ISSUE THREAD

**Issue by Nun-z** [SachinVin/citra_android#220]
I'm getting the following error message when trying to build:

arm_neon.h:65:24: error: 'neon_vector_type' attribute is not supported for this target.

In build.gradle, I have the following line: 
"-DANDROID_ARM_NEON=ON" // cryptopp requires Neon to work

This matches the docs here: https://developer.android.com/ndk/guides/cpu-arm-neon.html#per-app.  Where have I gone wrong?

**Comment by SachinVin** [comment]
Are you building for x86?

**Comment by Nun-z** [comment]
I'm trying to build for arm64.  I left x86 commented out next to abiFilters.

**Comment by Nun-z** [comment]
Nevermind, got it to work.  It runs fine when built with the backend in this project, but it crashes when launched if built with a new backend cloned from here: https://github.com/citra-emu/citra.

**Comment by ghost** [comment]
I get this error too when building on appveyor and I did several things to fix it but Nothing worked for me ( and I'm using SachinVin's Citra backend too ). Is there any specific line you've changed to get it to work? Because SachinVin's appveyor has been failing with this error too.

**Comment by ghost** [comment]
@SachinVin
Do you have any culprit in mind? 🤔
And is there a way to ignore all of the errors when building with appveyor and finish it anyway?

**Comment by Nun-z** [comment]
> I get this error too when building on appveyor and I did several things to fix it but Nothing worked for me ( and I'm using SachinVin's Citra backend too ). Is there any specific line you changed to get it to work? Because SachinVin's appveyor has been failing with this error too.

Replace line 74 of citra_android\app\build.gradle with: 

`abiFilters "arm64-v8a"//, "x86_64", "armeabi-v7a", "x86"`

**Comment by SachinVin** [comment]
Probably some 3rd party stuff with bad architecture detection

**Comment by ghost** [comment]
- Nun-z
I did that and I've got less errors but it failed with the ":app:PackageRelease" task anyway and after a few tries to address it, I gave up XD
But still! Thanks a lot! At least it gave me that one error instead of overflowing with errors ;)

- SachinVin
I did a quick analysis of past successful builds of appveyor from your repo and while I was comparing those logs with mine, the different version of Android SDK platform tools version catched my eye, in your past successful builds, appveyor used the version "28.0.1" but in my build it uses the "29.0.4" one. Can the issue be from the new Android SDK platform tools/Visual Studio image?

**Comment by Nun-z** [comment]
Is the error something about cubeb, speex?

**Comment by ghost** [comment]
No (though I had that error a year ago I think, what was causing it?!), appveyor actually succeeded to build after I commented out the "signingConfig signingConfigs.release" line of build.gradle ( after "too many errors" error, it turns out the second error that stopped appveyor from building was the Keys because It couldn't read or receive them I think so it said that those keys are empty and then failed to build) and it uploaded an unsigned apk, but I couldn't install it. It always fails to install and I dunno why, I'm pretty sure the kirin 970 uses armv8a architecture 🤔
Edit : Well now I'm getting that cubeb/speex error again after a year XD

**Comment by SachinVin** [comment]
You can't install an unsigned apk, if you are using appveyor replace the
jks file with your own and change the encrypted values in the appveyor.yml
to whatever is yours

**Comment by ghost** [comment]
I didn't know that 🤔 Thanks for telling me! And sorry if I don't know the most basic stuff about ci appveyor, I started building with it a few days ago 😅

Again, thanks for telling me that!

**Comment by Nun-z** [comment]
I think this issue should be closed.
