### ISSUE TITLE
Game wont even open

### ISSUE THREAD

**Issue by TrueMeltix** [SachinVin/citra_android#25]
When tapping on a game, it opens the emulator, shows controls ecc. After 5 secs it returns automatically to the menu.

**Comment by Paraskevidis** [comment]
You can't use this emulator if you don't have snapdragon.
Dev is working on a fix

**Comment by TrueMeltix** [comment]
@Paraskevidis Oh thank you, didnt know that

**Comment by KuyaJowell** [comment]
Hopefully sachinvin will add speed hack or frameskip in the future updates so mid-range fon can play too >•< coz atm its laggy

**Comment by wesleyvanneck** [comment]
Am not very hypt we shouldn't expect much because one there is only one dev and it does only work on snapdragon not on any other processor  in Europe Samsung sells only exynos processors

**Comment by Paraskevidis** [comment]
I'm hyped because this one man made this port to an older version of citra and it's still in early stages BUT can run games like Pokemon with a good speed (watch YouTube videos)

And the official Citra team is working on their own port for Android and may work together with SachinVin so great times may be ahead of us (I read about this in the emulation sub in Reddit)

**Comment by TrueMeltix** [comment]
@Paraskevidis good, but we're getting off topic

**Comment by AlvinZp** [comment]
Make sure the GPU support the Citra.What I know is Mali and Snapdragon is not supported

**Comment by yannosalex200** [comment]
Does it work on media tek
