### ISSUE TITLE
Citra does not view game files.

### ISSUE THREAD

**Issue by Ragonfana** [SachinVin/citra_android#37]
When opening Citra and using the plus sign in the bottom right corner, Citra will open my phone's files, but will seemingly be unable to see any game files. Screenshots are included, showing what Citra is seeing, and what is actually in the selected folder. Phone is an LG V20 running Android 7.0. Apologies for very large screenshots.
![capture _2018-10-11-09-16-39](https://user-images.githubusercontent.com/13308218/46807083-299f4800-cd37-11e8-8bb0-15b0fca17b87.png)
![capture _2018-10-11-09-16-26](https://user-images.githubusercontent.com/13308218/46807231-71be6a80-cd37-11e8-9da2-51e828881a9e.png)

**Comment by wesleyvanneck** [comment]
What do you expect from a alpha

**Comment by Emulatorer** [comment]
don't expect too much :/

**Comment by Ragonfana** [comment]
@wesleyvanneck I know this is an alpha, but it's good to report bugs. I'm not expecting an immediate fix or anything of the sort, I just want people to be aware this is occuring.

**Comment by valentinvanelslande** [comment]
select the folder containing your games

**Comment by Ragonfana** [comment]
@valentinvanelslande The folder shown in both screenshots is the same - according to my phone and computer, it contains those .3ds files, however Citra does not see them.

**Comment by wesleyvanneck** [comment]
@kenan1099 how do whant games if dont have a 3ds etc

**Comment by HelloOO7** [comment]
@wesleyvanneck Buy the games, then dump them using another person's 3DS. That's the only legal way if you don't have one AFAIK.

**Comment by Ragonfana** [comment]
@HelloOO7 It's listed on the Citra website as a gray area at best, but you are right when it is the "most legal" way to get games for emulators. (Though, as far as I know, this method only really works on the 3DS anyway? Someone correct me if im wrong.)

**Comment by HelloOO7** [comment]
@Ragonfana If you buybuy a physical copy of a game, you own the code. The way you run this one very specific piece of code is entirely up to you. Using a friend's 3DS to dump it is completely legal, but if your game needed the system archives, then strictly speaking you need your own 3ds, as you don't "own" those (your friend does). And although Nintendo wants you to think that acquiring a game backup is bad (see their Emulation Policy page), they can't really do anything about it as there's a precedent for that. See the Bleem case. What falls into the gray area is when you buy a game and then instead of dumping it, you download it. It's ethically speaking correct, but as you only own *that one specific piece of code*, it's not really legal.

**Comment by ItsMeRusT** [comment]
Press the ok button once you have reached the folder that your game file is in it should pop up on the main screen

**Comment by SachinVin** [comment]
Like @ItsMeRusT said just click "OK" and it should show up

**Comment by HelloCrater** [comment]
Hello, I have the same issue. I tried the 'Ok' and it did not show up. I can only see the folders, no files, just folders. What should I do?

**Comment by michaelphagen** [comment]
> I can only see the folders, no files, just folders.

What folders are you talking about? are you inside the folder that has the .3ds files or are the folders that you see the ones that contain the .3ds files?
